### ISSUE TITLE
🐛 Fix: Always show bottom nav bar on mobile

### ISSUE THREAD

**Issue by atrefonas** [algodex/algodex-mailbox#115]
# ℹ Overview

For example right now I can't see it. It should be sticky on the bottom.

![image](https://user-images.githubusercontent.com/72869083/161082158-68eaabb0-9c06-4aed-b876-044fa3d016bd.png)

### 💻 System Configuration

- Operating System:
    - Edition: 
    - Version: 
    - Build: 
- Browser:
    - Type: 
    - Version:

**Comment by treasurechic** [comment]
@atrefonas  There is a bottom nav on mobile
![IMG_7033](https://user-images.githubusercontent.com/46996915/161114460-427801dc-e8d9-4a4d-8b14-5f099616358f.jpeg)
