### ISSUE TITLE
✨ Feature: Allow searching for assets in all asset id fields

### ISSUE THREAD

**Issue by atrefonas** [algodex/algodex-mailbox#116]
# ℹ Overview

Allow searching for Asset Id or Asset Name similar to how Algo Explorer does it. Then put the full name with the asset id into the asset id field. The underlying value should be the number itself.

![image](https://user-images.githubusercontent.com/72869083/161082573-ef15a161-7bd1-42a0-8d8a-cd4dc690452d.png)

Use the Algoexplorer API: https://indexer.algoexplorerapi.io/rl/v1/search?keywords=frog

**Comment by treasurechic** [comment]
@atrefonas , this endpoint returns CORS error. Unable to hit the endpoint from my end, I don't think they will give direct access to external call like that.
