### ISSUE TITLE
✨ Feature: Add landing page in light mode

### ISSUE THREAD

**Issue by atrefonas** [algodex/algodex-mailbox#143]
# ℹ Overview

Add Steph's designs into the next.js project and make it the new ./pages/index.js. This does **not** need to use MUI components since it's just a landing page.

https://www.figma.com/file/3mUNzhDN7whCLAMlykP8UY/Mailbox-Landing-Page?node-id=0%3A1

[MailboxPageLight2.pdf](https://github.com/algodex/algodex-mailbox/files/8413136/MailboxPageLight2.pdf)

"Hope everyone is having a good Monday! :sunny:
I've been working on a landing page for Algodex Mailbox. It's simple with a brief overview of the tool and directs to the App, User Guide, and FAQ. We can add future sections with stats and projects that have used it for airdrops for example. I also just used a few FAQs - we can decide which ones are needed here (This section is also expandable so it's not just a ton of text). Let me know any feedback! There's a light and dark version but they are the same otherwise" -Steph

**Comment by stephclarkga** [comment]
Mobile versions have been added to the Figma file linked above. Icons/Illustration assets can be found and downloaded from this folder: https://app.box.com/s/ez76elqi0s1zkf28i9r5lop6aygd7mnh
