### ISSUE TITLE
✨ Feature: Add radio button option to send to a single address

### ISSUE THREAD

**Issue by atrefonas** [algodex/algodex-mailbox#224]
# ℹ Overview

Add a new radio button options to send to a single address vs send to .CSV list

If sending to a single address, show a text box where they can enter the recipient address, and hide the "upload .CSV" form. It should also work with .algo

Also create cypress tests for both options.

**Comment by stephclarkga** [comment]
Adding these here:

<img width="1440" alt="Desktop - 7" src="https://user-images.githubusercontent.com/59464107/169382434-c49621fe-da65-44be-a33c-b3d3508971c1.png">

<img width="1440" alt="Desktop - 8" src="https://user-images.githubusercontent.com/59464107/169382329-e4c152ca-13e1-4dc0-b413-495631d65825.png">

<img width="1440" alt="Desktop - 9" src="https://user-images.githubusercontent.com/59464107/169382344-ab1fa469-1b38-452d-b9cd-a19824975a1b.png">
