### ISSUE TITLE
Support Link Update

### ISSUE THREAD

**Issue by adam-algonaut** [algodex/algodex-mailbox#257]
Support Link on Algodex Mailbox redirects to old support page (https://about.algodex.com/support/). Please update with new link.

**Comment by treasurechic** [comment]
@adam-algonaut , can you send a screenshot of where this support link is located on the website?..........all the support links routes to this page: "https://app.algodex.com/support/"

**Comment by adam-algonaut** [comment]
@treasurechic see attached image. I also circled the other issue link that needs to be changed too. Thank you!


![work1](https://user-images.githubusercontent.com/107652076/192902677-1f2f28b1-6dd6-4a6f-8ad4-8d337cdf1941.PNG)

**Comment by treasurechic** [comment]
Oh, I see the updates is yet to be merged to production

**Comment by atrefonas** [comment]
This is done
