### ISSUE TITLE
✨ Feature: After connecting a wallet in one page of the app, store it in global state and remember the connected wallets across the other pages, even for page refresh

### ISSUE THREAD

**Issue by atrefonas** [algodex/algodex-mailbox#90]
# ℹ Overview

**Comment by treasurechic** [comment]
@atrefonas , this is good. Do you think we should clear it when the user closes the app or we leave it so they can continue with the same data later?

**Comment by atrefonas** [comment]
No, it should not be cleared when they close the app. It should remain in the browser cache

**Comment by treasurechic** [comment]
> No, it should not be cleared when they close the app. It should remain in the browser cache

Okay
